/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AiDisclosureRouteImport } from './routes/ai-disclosure'
import { Route as AportaRouteImport } from './routes/aporta'
import { Route as BarriosRouteImport } from './routes/barrios'
import { Route as ComerRouteImport } from './routes/comer'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as RedaccionRouteImport } from './routes/redaccion'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TestRouteImport } from './routes/test'
import { Route as GIdRouteImport } from './routes/g.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDisclosureRoute = AiDisclosureRouteImport.update({
  id: '/ai-disclosure',
  path: '/ai-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AportaRoute = AportaRouteImport.update({
  id: '/aporta',
  path: '/aporta',
  getParentRoute: () => rootRouteImport,
} as any)
const BarriosRoute = BarriosRouteImport.update({
  id: '/barrios',
  path: '/barrios',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerRoute = ComerRouteImport.update({
  id: '/comer',
  path: '/comer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedaccionRoute = RedaccionRouteImport.update({
  id: '/redaccion',
  path: '/redaccion',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const GIdRoute = GIdRouteImport.update({
  id: '/g/$id',
  path: '/g/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-disclosure': typeof AiDisclosureRoute
  '/aporta': typeof AportaRoute
  '/barrios': typeof BarriosRoute
  '/comer': typeof ComerRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/guides': typeof GuidesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/recursos': typeof RecursosRoute
  '/redaccion': typeof RedaccionRoute
  '/sobre': typeof SobreRoute
  '/test': typeof TestRoute
  '/g/$id': typeof GIdRoute
  '/p/$slug': typeof PSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-disclosure': typeof AiDisclosureRoute
  '/aporta': typeof AportaRoute
  '/barrios': typeof BarriosRoute
  '/comer': typeof ComerRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/guides': typeof GuidesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/recursos': typeof RecursosRoute
  '/redaccion': typeof RedaccionRoute
  '/sobre': typeof SobreRoute
  '/test': typeof TestRoute
  '/g/$id': typeof GIdRoute
  '/p/$slug': typeof PSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-disclosure': typeof AiDisclosureRoute
  '/aporta': typeof AportaRoute
  '/barrios': typeof BarriosRoute
  '/comer': typeof ComerRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/guides': typeof GuidesRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/pulse': typeof PulseRoute
  '/recursos': typeof RecursosRoute
  '/redaccion': typeof RedaccionRoute
  '/sobre': typeof SobreRoute
  '/test': typeof TestRoute
  '/g/$id': typeof GIdRoute
  '/p/$slug': typeof PSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/ai-disclosure'
    | '/aporta'
    | '/barrios'
    | '/comer'
    | '/feed.xml'
    | '/guides'
    | '/legal'
    | '/login'
    | '/privacy'
    | '/pulse'
    | '/recursos'
    | '/redaccion'
    | '/sobre'
    | '/test'
    | '/g/$id'
    | '/p/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/ai-disclosure'
    | '/aporta'
    | '/barrios'
    | '/comer'
    | '/feed.xml'
    | '/guides'
    | '/legal'
    | '/login'
    | '/privacy'
    | '/pulse'
    | '/recursos'
    | '/redaccion'
    | '/sobre'
    | '/test'
    | '/g/$id'
    | '/p/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/ai-disclosure'
    | '/aporta'
    | '/barrios'
    | '/comer'
    | '/feed.xml'
    | '/guides'
    | '/legal'
    | '/login'
    | '/privacy'
    | '/pulse'
    | '/recursos'
    | '/redaccion'
    | '/sobre'
    | '/test'
    | '/g/$id'
    | '/p/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AiDisclosureRoute: typeof AiDisclosureRoute
  AportaRoute: typeof AportaRoute
  BarriosRoute: typeof BarriosRoute
  ComerRoute: typeof ComerRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  GuidesRoute: typeof GuidesRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PulseRoute: typeof PulseRoute
  RecursosRoute: typeof RecursosRoute
  RedaccionRoute: typeof RedaccionRoute
  SobreRoute: typeof SobreRoute
  TestRoute: typeof TestRoute
  GIdRoute: typeof GIdRoute
  PSlugRoute: typeof PSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-disclosure': {
      id: '/ai-disclosure'
      path: '/ai-disclosure'
      fullPath: '/ai-disclosure'
      preLoaderRoute: typeof AiDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aporta': {
      id: '/aporta'
      path: '/aporta'
      fullPath: '/aporta'
      preLoaderRoute: typeof AportaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrios': {
      id: '/barrios'
      path: '/barrios'
      fullPath: '/barrios'
      preLoaderRoute: typeof BarriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comer': {
      id: '/comer'
      path: '/comer'
      fullPath: '/comer'
      preLoaderRoute: typeof ComerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaccion': {
      id: '/redaccion'
      path: '/redaccion'
      fullPath: '/redaccion'
      preLoaderRoute: typeof RedaccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$id': {
      id: '/g/$id'
      path: '/g/$id'
      fullPath: '/g/$id'
      preLoaderRoute: typeof GIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AiDisclosureRoute: AiDisclosureRoute,
  AportaRoute: AportaRoute,
  BarriosRoute: BarriosRoute,
  ComerRoute: ComerRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  GuidesRoute: GuidesRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PulseRoute: PulseRoute,
  RecursosRoute: RecursosRoute,
  RedaccionRoute: RedaccionRoute,
  SobreRoute: SobreRoute,
  TestRoute: TestRoute,
  GIdRoute: GIdRoute,
  PSlugRoute: PSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
